export type VisualEvent = {
  id: number;
  op: string;
  label: string;
  detail: string;
  assertion: string;
  storage: string;
  fromSlot: number;
  toSlot: number;
  value: string;
  sourceFile: string;
  sourceAnchor: string;
  sourceLine: number;
};

export type VisualCase = {
  scenario: string;
  title: string;
  coveredBy: {
    file: string;
    test: string;
  };
  events: VisualEvent[];
};

function event(
  id: number,
  op: string,
  label: string,
  storage: string,
  fromSlot = -1,
  toSlot = -1,
  value = "",
  sourceAnchor = "",
  detail = "",
  assertion = "",
): VisualEvent {
  return {
    id,
    op,
    label,
    detail,
    assertion,
    storage,
    fromSlot,
    toSlot,
    value,
    sourceFile: "include/chaistl/containers/sequence/vector.hpp",
    sourceAnchor,
    sourceLine: 0,
  };
}

export const visualCases: VisualCase[] = [
  {
    scenario: "vector.test.reallocation_insert_preserves_order",
    title: "insert reallocates and preserves order",
    coveredBy: {
      file: "test/chaistl/containers/sequence/vector/modifiers.cpp",
      test: "SingleInsertWithReallocationPreservesOrder",
    },
    events: [
      event(
        0,
        "snapshot",
        "prepare full storage",
        "old",
        -1,
        -1,
        "1,3,4",
        "",
        "The test creates three live objects and reserves exactly three slots. There is no spare capacity, so inserting one more value must allocate a different storage block.",
        "old_capacity == 3 before insert",
      ),
      event(
        1,
        "api_call",
        "call insert at position 1",
        "old",
        -1,
        -1,
        "",
        "",
        "The public API asks for the value 2 to appear before the old element 3. The interesting internal path is selected because size() + 1 is greater than capacity().",
        "auto it = values.insert(values.begin() + 1, 2)",
      ),
      event(
        2,
        "allocate",
        "allocate raw candidate storage",
        "new",
        -1,
        -1,
        "6",
        "vector.reallocate_and_emplace_at.allocate",
        "Allocation only reserves uninitialized storage. No T object exists in the new block yet, so the UI marks all slots as raw.",
        "values is still unchanged if allocation throws",
      ),
      event(
        3,
        "construct",
        "construct inserted object first",
        "new",
        -1,
        1,
        "2",
        "vector.reallocate_and_emplace_at.construct_inserted",
        "The new value is constructed directly at its final offset. This avoids a temporary layout and makes the target order visible early: slot 1 is reserved for the inserted element.",
        "*it will refer to this object after commit",
      ),
      event(
        4,
        "move_construct",
        "relocate prefix",
        "new",
        0,
        0,
        "1",
        "vector.reallocate_and_emplace_at.move_prefix",
        "Elements before the insertion point keep the same index. They are move-constructed into the candidate storage without changing the final order.",
        "values[0] remains 1",
      ),
      event(
        5,
        "move_construct",
        "relocate first suffix element",
        "new",
        1,
        2,
        "3",
        "vector.reallocate_and_emplace_at.move_suffix",
        "Elements at or after the insertion point shift by one slot. The old 3 moves from slot 1 to slot 2.",
        "values[2] will become 3",
      ),
      event(
        6,
        "move_construct",
        "relocate remaining suffix",
        "new",
        2,
        3,
        "4",
        "vector.reallocate_and_emplace_at.move_suffix",
        "The old 4 is the final suffix element. After this step, the candidate storage already contains the final logical sequence.",
        "values[3] will become 4",
      ),
      event(
        7,
        "commit_storage",
        "commit pointer triple",
        "new",
        -1,
        -1,
        "",
        "vector.reallocate_and_emplace_at.commit",
        "Only after every object is constructed does vector replace first_, last_, and capacity_last_. This is the commit point of the transaction.",
        "values.capacity() > old_capacity",
      ),
      event(
        8,
        "deallocate",
        "release old storage",
        "old",
        -1,
        -1,
        "",
        "",
        "The old block is no longer the vector storage. Its moved-from elements are gone and the raw memory can be returned to the allocator.",
        "old iterators are invalidated by reallocation",
      ),
      event(
        9,
        "snapshot",
        "verify final order",
        "new",
        -1,
        -1,
        "1,2,3,4",
        "",
        "The visual sequence now matches the gtest expectation. The returned iterator points at slot 1, the inserted value.",
        "std::ranges::equal(values, std::array{1, 2, 3, 4})",
      ),
    ],
  },
  {
    scenario: "vector.test.reallocation_insert_self_reference",
    title: "insert handles self-reference before moving old elements",
    coveredBy: {
      file: "test/chaistl/containers/sequence/vector/modifiers.cpp",
      test: "ReallocationInsertHandlesSelfReferenceBeforeMovedPrefix",
    },
    events: [
      event(
        0,
        "snapshot",
        "prepare full storage",
        "old",
        -1,
        -1,
        "11,22,33",
        "",
        "The test uses MoveMarksSource so moving an old object is observable. This makes self-reference ordering bugs visible.",
        "values.front().value == 11 before insert",
      ),
      event(
        1,
        "api_call",
        "insert a reference into the same vector",
        "old",
        -1,
        -1,
        "",
        "",
        "The inserted argument refers to old slot 0. If slot 0 were moved before constructing the inserted value, the insertion could observe a moved-from object.",
        "values.insert(values.begin() + 2, values.front())",
      ),
      event(
        2,
        "allocate",
        "allocate without touching old objects",
        "new",
        -1,
        -1,
        "6",
        "vector.reallocate_and_emplace_at.allocate",
        "The old storage remains fully live after allocation. This matters because the inserted value still needs to read values.front().",
        "old slot 0 is still 11",
      ),
      event(
        3,
        "construct",
        "copy self-reference into final slot",
        "new",
        0,
        2,
        "11",
        "vector.reallocate_and_emplace_at.construct_inserted",
        "This is the key teaching step. The inserted value is constructed from values.front() before any prefix move can mutate the referenced source object.",
        "values[2].value will be 11",
      ),
      event(
        4,
        "move_construct",
        "relocate prefix slot 0",
        "new",
        0,
        0,
        "11",
        "vector.reallocate_and_emplace_at.move_prefix",
        "Now it is safe to move old slot 0, because the inserted copy has already captured its value.",
        "moved-from old slot 0 no longer affects inserted slot 2",
      ),
      event(
        5,
        "move_construct",
        "relocate prefix slot 1",
        "new",
        1,
        1,
        "22",
        "vector.reallocate_and_emplace_at.move_prefix",
        "The second prefix element keeps its index. The candidate storage now has both prefix elements and the inserted value.",
        "values[1].value will be 22",
      ),
      event(
        6,
        "move_construct",
        "relocate suffix after inserted slot",
        "new",
        2,
        3,
        "33",
        "vector.reallocate_and_emplace_at.move_suffix",
        "The old element at the insertion position shifts one slot to the right, after the inserted self-reference copy.",
        "values[3].value will be 33",
      ),
      event(
        7,
        "commit_storage",
        "commit after all construction succeeds",
        "new",
        -1,
        -1,
        "",
        "vector.reallocate_and_emplace_at.commit",
        "The vector publishes the new storage only after the candidate block contains a complete valid sequence.",
        "values.size() == 4",
      ),
      event(
        8,
        "deallocate",
        "release old storage",
        "old",
        -1,
        -1,
        "",
        "",
        "The old block has served its purpose. Every live value needed by the final vector has been constructed in the new block.",
        "reallocation invalidates old references and iterators",
      ),
      event(
        9,
        "snapshot",
        "verify self-reference result",
        "new",
        -1,
        -1,
        "11,22,11,33",
        "",
        "The inserted 11 proves why the implementation constructs the new element before moving prefix elements.",
        "values[0..3] == 11, 22, 11, 33",
      ),
    ],
  },
];
